### ISSUE TITLE
No correctly naming attachment

### ISSUE THREAD

**Issue by octplane** [exomut/evernote-dump#17]
On my version of export, I have to create the filenames this way:

```python
    def get_attribute(self, name):
        return "".join(val[1] for val in self._attributes if val[0] == name).strip()

    def create_filename(self, keep_file_names):
        self._filename = self.get_attribute("file-name")
        base = self._filename
        [...]
```

Not sure this is a problem for others though...

```xml
     <resource-attributes>
        <file-name>test.pdf</file-name>
```

**Comment by exomut** [comment]
Thanks for contacting. The ability to use filenames needs to be turned on by using the `-p` flag in command line or checking the preserve file names box in the GUI. I have it set to default to not use original filenames since it was creating problems with some long names and/or foreign languages.

I should have me the label for the check box a little bit clearer. Let me know if it is still an issue.
