### ISSUE TITLE
no evernote_dump

### ISSUE THREAD

**Issue by ImolaS3** [exomut/evernote-dump#21]
There seems to be no evernote_dump file to run and i get errors when i try to use this

there is a dump.py but that doesn't;t run

**Comment by ImolaS3** [comment]
my terminal window gioves this - i am probably doing something wrong 
>>> python -m /Users/antonysutton/Downloads/evernote-dump/evernote_dump/dump.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'python' is not defined
>>> python -m /Users/antonysutton/Downloads/evernote-dump/evernote_dump/gui.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'python' is not defined
>>> python -m /Users/antonysutton/Downloads/evernote-dump/evernote_dump/gui.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'python' is not defined
>>>

**Comment by exomut** [comment]
It looks like you don't have Python installed or it is not included in your system PATH.

If you are not familiar with Python, it is a scripting language that is used to make tools easily. Evernote Dump requires it. Evernote Dump is not a standalone executable so it can be run on many different operating systems.

You will need Python version 3. Please go to [Python's Download Page](https://www.python.org/downloads/) to download and install the latest version. After installing, the `python` command should be added to your system PATH.

Once that is complete, you are ready to setup Evernote Dump. Go to the [README.md file](https://github.com/exomut/evernote-dump/blob/master/README.md) for the project and follow each step. Make sure to move to the correct folder before starting; which is the folder containing the `evernote-dump` folder.

If you are having problems installing `Python` and getting the `python` command to run. Try searching google for `install python on` and the name of your operating system, since it is different for each system.

If you are unfamiliar with using the terminal, here is a [quick tutorial](https://linux.die.net/Linux-CLI/using-filesystem.html) on changing folders and moving around in the terminal.

Good luck!

**Comment by exomut** [comment]
It looks like you don't have Python installed or it is not included in your system PATH.

If you are not familiar with Python, it is a scripting language that is used to make tools easily. Evernote Dump requires it. Evernote Dump is not a standalone executable so it can be run on many different operating systems.

You will need Python version 3. Please go to [Python's Download Page](https://www.python.org/downloads/) to download and install the latest version. After installing, the `python` command should be added to your system PATH.

Once that is complete, you are ready to setup Evernote Dump. Go to the [README.md file](https://github.com/exomut/evernote-dump/blob/master/README.md) for the project and follow each step. Make sure to move to the correct folder before starting; which is the folder containing the `evernote-dump` folder.

If you are having problems installing `Python` and getting the `python` command to run. Try searching google for `install python on` and the name of your operating system, since it is different for each system.

Good luck!
